spring:
  application:
    name: kotlin-querydsl
  datasource:
    url: jdbc:mysql://192.168.33.24:3308/playground
    username: root
    password: strong-password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
